
name: Create release on tag creation

on:
  push:
    tags:
      - "v*"

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - name: Get tag name
        id: tag
        uses: dawidd6/action-get-tag@v1

      - name: Create a release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          title: "${{ steps.tag.outputs.tag }}"
